apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
      - name: speedtest
        image: gcr.io/qwiklabs-gcp-03-5186302bd920/speedtest:latest
        ports:
        - containerPort: 80
