name: Speed Test CI

on:
  schedule:
    - cron: '0 * * * *'  # This runs the workflow every hour
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  speed-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run speed test
      run: |
        source venv/bin/activate
        python main.py

    - name: Upload log file
      uses: actions/upload-artifact@v3
      with:
        name: speedtest-log
        path: data/logs/speedtest.log

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: pallakki/speedtest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

